# Generated by Django 5.0 on 2024-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0009_remove_comment_user_comment_name_alter_comment_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carlist/media/uploads/'),
        ),
    ]
